name: test

on:
  push:
    branches:
      - "*"

jobs:
  install-fontawesome:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10]
    name: Node ${{ matrix.node }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install
